// apps/react-host-platform/src/pages/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import PlatformTourModal from '../components/common/PlatformTourModal';

export const Login: React.FC = () => {
  const navigate = useNavigate();
  const [username, setUsername] = useState('chief_admin');
  const [password, setPassword] = useState('admin123');
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState('');
  const [isTourOpen, setIsTourOpen] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitted(true);

    if (!username || !password) return;

    if (username === 'chief_admin' && password === 'admin123') {
      const mockSession = {
        id: 'usr-001',
        username: 'chief_admin',
        name: 'Alex Mercer',
        role: 'OPERATIONS_MANAGER',
        token: 'mock-jwt-super-admin-token-xyz'
      };

      localStorage.setItem('host_session', JSON.stringify(mockSession));
      navigate('/dashboard');
    } else {
      setError('Unauthorized credentials.');
    }
  };

  const handleGuestLogin = () => {
    const mockSession = {
      id: 'usr-guest',
      username: 'guest_explorer',
      name: 'Guest Reviewer',
      role: 'PORTFOLIO_VISITOR',
      token: 'guest-bypass-token'
    };

    localStorage.setItem('host_session', JSON.stringify(mockSession));
    navigate('/dashboard');
  };

  return (
    <div className="d-flex align-items-center justify-content-center min-vh-100 bg-primary px-3 flex-column">
      {/* Onboarding Guide Trigger */}
      <div className="mb-4 text-center">
        <button 
          onClick={() => setIsTourOpen(true)}
          className="btn btn-sm btn-outline-secondary px-3 py-2 text-secondary font-monospace"
          style={{
            borderRadius: '20px',
            borderColor: 'rgba(255,255,255,0.1)',
            background: 'rgba(255,255,255,0.02)',
            letterSpacing: '0.5px',
            fontSize: '0.78rem'
          }}
        >
          <i className="fa-solid fa-circle-info me-2 text-indigo" style={{ color: '#6366f1' }}></i>
          New here? Explore Platform Tour
        </button>
      </div>

      <div className="card bg-secondary text-light border-secondary p-4 shadow-lg" style={{ maxWidth: '390px', width: '100%', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.08) !important' }}>
        <div className="text-center mb-4">
          <div className="logo-icon bg-indigo mx-auto mb-3" style={{ width: '36px', height: '36px', background: '#5b5df6', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontWeight: 800, fontSize: '1.1rem', lineHeight: '36px' }}>F</div>
          <h4 className="text-white font-weight-extrabold mb-1" style={{ letterSpacing: '-0.5px' }}>Sign In</h4>
          <p className="text-secondary small">Access the FinTransit Operations Platform</p>
        </div>

        {error && (
          <div className="alert alert-danger py-2 px-3 small border-danger-subtle mb-3" role="alert">
            <i className="fa-solid fa-triangle-exclamation me-1"></i> {error}
          </div>
        )}

        <form onSubmit={handleSubmit} noValidate>
          <div className="form-group mb-3">
            <label className="text-secondary small font-monospace mb-1" style={{ fontSize: '0.65rem', letterSpacing: '0.5px' }}>USERNAME</label>
            <input 
              type="text" 
              className={`form-control text-white border-secondary ${submitted && !username ? 'is-invalid' : ''}`}
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="e.g. chief_admin"
              style={{ padding: '0.6rem 0.8rem', fontSize: '0.9rem' }}
            />
            {submitted && !username && (
              <div className="invalid-feedback">Username is required.</div>
            )}
          </div>

          <div className="form-group mb-4">
            <label className="text-secondary small font-monospace mb-1" style={{ fontSize: '0.65rem', letterSpacing: '0.5px' }}>PASSWORD</label>
            <input 
              type="password" 
              className={`form-control text-white border-secondary ${submitted && !password ? 'is-invalid' : ''}`}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="••••••••"
              style={{ padding: '0.6rem 0.8rem', fontSize: '0.9rem' }}
            />
            {submitted && !password && (
              <div className="invalid-feedback">Password is required.</div>
            )}
          </div>

          <button type="submit" className="btn btn-primary w-100 py-2.5 font-weight-bold mb-3" style={{ background: '#5b5df6', border: 'none', borderRadius: '8px', fontSize: '0.9rem' }}>
            Open Dashboard
          </button>
        </form>

        <div className="position-relative text-center my-3">
          <hr className="border-secondary opacity-20" />
          <span className="position-absolute top-50 start-50 translate-middle px-3 bg-secondary text-tertiary small font-monospace" style={{ fontSize: '0.68rem', letterSpacing: '0.5px' }}>OR</span>
        </div>

        {/* Guest Mode Direct Bypass Action */}
        <button 
          onClick={handleGuestLogin}
          className="btn btn-outline-primary w-100 py-2.5 d-flex align-items-center justify-content-center gap-2"
          style={{
            borderColor: 'rgba(99, 102, 241, 0.4)',
            color: '#a5b4fc',
            background: 'rgba(99, 102, 241, 0.04)',
            borderRadius: '8px',
            fontSize: '0.9rem',
            fontWeight: 600
          }}
        >
          <i className="fa-solid fa-bolt text-warning"></i>
          Explore as Guest (Fast Track)
        </button>
      </div>

      {/* Embedded Onboarding Tour Modal */}
      <PlatformTourModal 
        isOpen={isTourOpen}
        onClose={() => setIsTourOpen(false)}
        onStartGuestMode={handleGuestLogin}
      />
    </div>
  );
};
export default Login;

// apps/angular-healthcare-module/src/app/features/auth/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { NotificationService } from '../../core/services/notification.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div class="d-flex align-items-center justify-content-center min-vh-100 bg-primary">
      <div class="card bg-dark text-light border-secondary p-4" style="max-width: 420px; width: 100%;">
        <div class="text-center mb-4">
          <span class="badge bg-danger mb-2">CLINICAL SUITE ACCESS</span>
          <h4 class="text-white">Healthcare Care Portal</h4>
          <p class="text-secondary small">Enter clinical credentials to manage member health registries.</p>
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" novalidate>
          <div class="form-group">
            <label>CORPORATE USERNAME</label>
            <input 
              type="text" 
              formControlName="username" 
              class="form-control" 
              [class.is-invalid]="submitted && f['username'].errors"
              placeholder="e.g. clinical_lead"
            >
            <div class="invalid-feedback" *ngIf="submitted && f['username'].errors">
              Username is required (min 4 characters).
            </div>
          </div>

          <div class="form-group">
            <label>PASSWORD</label>
            <input 
              type="password" 
              formControlName="password" 
              class="form-control" 
              [class.is-invalid]="submitted && f['password'].errors"
              placeholder="••••••••"
            >
            <div class="invalid-feedback" *ngIf="submitted && f['password'].errors">
              Password is required (min 6 characters).
            </div>
          </div>

          <button type="submit" class="btn btn-danger w-100 clinical-btn mt-3">
            <i class="fa-solid fa-right-to-bracket me-1"></i> Sign In to Clinical Vault
          </button>
        </form>

        <div class="mt-4 p-2 bg-secondary bg-opacity-25 rounded text-center small text-secondary">
          <i class="fa-solid fa-circle-info text-info me-1"></i>
          Role: <code>CLINICAL_MANAGER</code>
        </div>
      </div>
    </div>
  `
})
export class LoginComponent {
  loginForm: FormGroup;
  submitted = false;

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private notifyService: NotificationService
  ) {
    this.loginForm = this.fb.group({
      username: ['clinical_lead', [Validators.required, Validators.minLength(4)]],
      password: ['clinical123', [Validators.required, Validators.minLength(6)]]
    });
  }

  get f() { return this.loginForm.controls; }

  onSubmit() {
    this.submitted = true;

    if (this.loginForm.invalid) return;

    const { username } = this.loginForm.value;

    if (username === 'clinical_lead') {
      const mockSession = {
        username: 'clinical_lead',
        role: 'CLINICAL_MANAGER',
        name: 'Stephen Strange',
        token: 'mock-jwt-clinical-98765'
      };
      
      localStorage.setItem('user_session', JSON.stringify(mockSession));
      this.notifyService.show('Welcome to Clinical Registries', 'success');
      this.router.navigate(['/']);
    } else {
      this.notifyService.show('Unauthorized corporate role.', 'danger');
    }
  }
}
